In [437]:
import pandas as pd
import numpy as np
import torch

vector_a = torch.tensor([11, 9, 5, 1])
print(type(vector_a))

<class 'torch.Tensor'>


In [438]:
print(f"نوع متغیر (باید تنسور باشد): {type(vector_a)}")

# 3. بررسی بُعد (Shape) و رتبه (Rank/Dim)
print(f"بُعد تنسور (Shape): {vector_a.shape}")

# 4. بررسی نوع داده داخلی (Dtype)
print(f"نوع داده داخلی (Dtype): {vector_a.dtype}")

نوع متغیر (باید تنسور باشد): <class 'torch.Tensor'>
بُعد تنسور (Shape): torch.Size([4])
نوع داده داخلی (Dtype): torch.int64


In [439]:
sep = "-" * 20
matrix_a = torch.tensor([[[10, 20, 30], [40, 50, 60]], [[70, 80, 90], [100, 110, 120]]])
print(f"Matrix_a : {matrix_a} \n\n {sep} \n \n Matrix_a.Shape : {matrix_a.shape}")

Matrix_a : tensor([[[ 10,  20,  30],
         [ 40,  50,  60]],

        [[ 70,  80,  90],
         [100, 110, 120]]]) 

 -------------------- 
 
 Matrix_a.Shape : torch.Size([2, 2, 3])


In [440]:
tensor_array = np.array([[[10, 20, 30], [40, 50, 60]], [[70, 80, 90], [100, 110, 120]]])
tensor_array = tensor_array.astype(np.int64)
tensor_furm = torch.tensor(tensor_array)
print(tensor_furm)

tensor([[[ 10,  20,  30],
         [ 40,  50,  60]],

        [[ 70,  80,  90],
         [100, 110, 120]]])


In [441]:
# 1. ایجاد آرایه‌ی NumPy ۲×۲ با dtype استاندارد float32 (برای محاسبات AI)
numpy_array = np.array([[1.0, 2.0], [3.0, 4.0]], dtype=np.float32)

# 2. تبدیل به Tensor
torch_tensor = torch.tensor(numpy_array)

# 3. پرینت مشخصات
print(f"NumPy Array Type: {type(numpy_array)}")
print(f"NumPy Array Shape: {numpy_array.shape}")
print("-" * 30)
print(f"PyTorch Tensor Type: {type(torch_tensor)}")
print(f"PyTorch Tensor Shape: {torch_tensor.shape}")
print(f"PyTorch Tensor Dtype: {torch_tensor.dtype}")

NumPy Array Type: <class 'numpy.ndarray'>
NumPy Array Shape: (2, 2)
------------------------------
PyTorch Tensor Type: <class 'torch.Tensor'>
PyTorch Tensor Shape: torch.Size([2, 2])
PyTorch Tensor Dtype: torch.float32


In [442]:
print(tensor_array)

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]]


In [443]:
t1 = torch.tensor([[1.0, 2.0, 9.0], [3.0, 4.0, 10.0]])
t2 = torch.tensor([[5.0, 6.0], [7.0, 8.0], [11.0, 12.0]])


t_mul = t1 @ t2

print(f"Tensor t1:\n{t1}")
print(f"\nTensor t2:\n{t2}")
print("-" * 30)
print(f"\nنتیجه ضرب (t_mul):\n{t_mul}")

Tensor t1:
tensor([[ 1.,  2.,  9.],
        [ 3.,  4., 10.]])

Tensor t2:
tensor([[ 5.,  6.],
        [ 7.,  8.],
        [11., 12.]])
------------------------------

نتیجه ضرب (t_mul):
tensor([[118., 130.],
        [153., 170.]])


In [444]:
t1 = torch.tensor([[1.0, 2.0, 9.0], [3.0, 4.0, 10.0]])
t1t = t1.T
moz1 = t1t @ t1
moz2 = t1 @ t1t
print(moz1)
print("-" * 30)
print(moz2)

tensor([[ 10.,  14.,  39.],
        [ 14.,  20.,  58.],
        [ 39.,  58., 181.]])
------------------------------
tensor([[ 86., 101.],
        [101., 125.]])


In [445]:
v = torch.tensor([1, 2, 3, 4, 5])
v0 = v.unsqueeze(0)
v1 = v.unsqueeze(1)
v_mul = v0 @ v1
print(v)
print(v0)
print(v1)
print(v_mul)

tensor([1, 2, 3, 4, 5])
tensor([[1, 2, 3, 4, 5]])
tensor([[1],
        [2],
        [3],
        [4],
        [5]])
tensor([[55]])


In [446]:
v0sd = v0.squeeze()
v1sd = v1.squeeze()
v_mulsd = v_mul.squeeze()
print(v0sd)
print(v1sd)
print(v_mulsd)
print(v_mul * 2)
v_mul = v_mul * 2
gay = v_mul.squeeze()
print(gay)

tensor([1, 2, 3, 4, 5])
tensor([1, 2, 3, 4, 5])
tensor(55)
tensor([[110]])
tensor(110)


In [447]:
def printrd():
    kos = "-" * 60
    print(f"\n \n \n {kos} \n\n")


moz = torch.rand(1, 4, 25)
moz_reshaped = moz.view(1, 4, 5, 5)
final_quaery = moz_reshaped.transpose(3, 2)
print(moz)
printrd()
print(final_quaery)

tensor([[[0.4196, 0.4088, 0.4995, 0.2043, 0.9414, 0.6512, 0.8704, 0.7530,
          0.0450, 0.1876, 0.4968, 0.7600, 0.9072, 0.9512, 0.1360, 0.5101,
          0.4524, 0.6724, 0.2694, 0.4593, 0.0426, 0.2852, 0.8793, 0.1002,
          0.6838],
         [0.5778, 0.1608, 0.5682, 0.4897, 0.2607, 0.6611, 0.6000, 0.4861,
          0.2228, 0.4773, 0.2370, 0.5320, 0.1601, 0.6257, 0.5924, 0.0951,
          0.6482, 0.8281, 0.4304, 0.7006, 0.0265, 0.5059, 0.3438, 0.9802,
          0.4789],
         [0.6977, 0.3247, 0.8808, 0.6960, 0.6252, 0.9946, 0.3312, 0.7548,
          0.3733, 0.1869, 0.9993, 0.6560, 0.5633, 0.3914, 0.5511, 0.3011,
          0.0294, 0.5585, 0.5172, 0.1409, 0.9698, 0.5685, 0.1234, 0.5639,
          0.5907],
         [0.7164, 0.3917, 0.6134, 0.1551, 0.8774, 0.5675, 0.4832, 0.6270,
          0.4150, 0.3660, 0.0717, 0.3270, 0.2329, 0.7133, 0.0609, 0.7468,
          0.7746, 0.4273, 0.5046, 0.4094, 0.0075, 0.1141, 0.3829, 0.7932,
          0.4163]]])

 
 
 ----------------------------

In [448]:
M = torch.rand(4, 5)
V = torch.tensor([1, 2, 3, 4])

V_col = V.unsqueeze(1)
# V_col1 = V.T
print(M * V_col)
# print(M * V)

tensor([[0.4821, 0.3649, 0.2842, 0.7962, 0.1796],
        [1.4719, 1.5433, 1.1162, 1.4190, 1.9964],
        [2.5922, 1.7045, 2.6941, 2.3630, 2.2078],
        [0.4784, 3.6905, 0.3315, 0.5892, 3.8286]])


In [449]:
x = torch.tensor(2.0, requires_grad=True)
y = 3 * x**2 + 5
print(f"y  {y} \n x : {x},\n gradian x : {x.grad} \n gradian y : {y.backward()}")

y  17.0 
 x : 2.0,
 gradian x : None 
 gradian y : None


In [ ]:
import torch

# 1. تعریف تنسور ورودی (a) با requires_grad=True
# a = [2.0, 3.0]
a = torch.tensor([1.0], requires_grad=True)

# 2. عملیات: b = 2a (اینجا b خروجی یا y است)
b = a**2 * 2**2

# 3. تعریف تنسور وزن گرادیان (v)
# v = [0.1, 1000.0]
v = torch.tensor([1.0])

# 4. محاسبه گرادیان نهایی (مشتق)
# PyTorch مشتق db/da را محاسبه و در v ضرب می‌کند
b.backward(v)

# 5. پرینت گرادیان نهایی ذخیره‌شده در a.grad
print(f"گرادیان a (a.grad): {a.grad}")
print(f"a : {b}")

گرادیان a (a.grad): tensor([8.8000])
a : tensor([4.8400], grad_fn=<MulBackward0>)
