In [299]:
import pandas as pd
import numpy as np
import torch

vector_a = torch.tensor([11, 9, 5, 1])
print(type(vector_a))

<class 'torch.Tensor'>


In [300]:
print(f"نوع متغیر (باید تنسور باشد): {type(vector_a)}")

# 3. بررسی بُعد (Shape) و رتبه (Rank/Dim)
print(f"بُعد تنسور (Shape): {vector_a.shape}")

# 4. بررسی نوع داده داخلی (Dtype)
print(f"نوع داده داخلی (Dtype): {vector_a.dtype}")

نوع متغیر (باید تنسور باشد): <class 'torch.Tensor'>
بُعد تنسور (Shape): torch.Size([4])
نوع داده داخلی (Dtype): torch.int64


In [301]:
sep = "-" * 20
matrix_a = torch.tensor([[[10, 20, 30], [40, 50, 60]], [[70, 80, 90], [100, 110, 120]]])
print(f"Matrix_a : {matrix_a} \n\n {sep} \n \n Matrix_a.Shape : {matrix_a.shape}")

Matrix_a : tensor([[[ 10,  20,  30],
         [ 40,  50,  60]],

        [[ 70,  80,  90],
         [100, 110, 120]]]) 

 -------------------- 
 
 Matrix_a.Shape : torch.Size([2, 2, 3])


In [302]:
tensor_array = np.array([[[10, 20, 30], [40, 50, 60]], [[70, 80, 90], [100, 110, 120]]])
tensor_array = tensor_array.astype(np.int64)
tensor_furm = torch.tensor(tensor_array)
print(tensor_furm)

tensor([[[ 10,  20,  30],
         [ 40,  50,  60]],

        [[ 70,  80,  90],
         [100, 110, 120]]])


In [303]:
# 1. ایجاد آرایه‌ی NumPy ۲×۲ با dtype استاندارد float32 (برای محاسبات AI)
numpy_array = np.array([[1.0, 2.0], [3.0, 4.0]], dtype=np.float32)

# 2. تبدیل به Tensor
torch_tensor = torch.tensor(numpy_array)

# 3. پرینت مشخصات
print(f"NumPy Array Type: {type(numpy_array)}")
print(f"NumPy Array Shape: {numpy_array.shape}")
print("-" * 30)
print(f"PyTorch Tensor Type: {type(torch_tensor)}")
print(f"PyTorch Tensor Shape: {torch_tensor.shape}")
print(f"PyTorch Tensor Dtype: {torch_tensor.dtype}")

NumPy Array Type: <class 'numpy.ndarray'>
NumPy Array Shape: (2, 2)
------------------------------
PyTorch Tensor Type: <class 'torch.Tensor'>
PyTorch Tensor Shape: torch.Size([2, 2])
PyTorch Tensor Dtype: torch.float32


In [304]:
print(tensor_array)

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]]


In [305]:
t1 = torch.tensor([[1.0, 2.0, 9.0], [3.0, 4.0, 10.0]])
t2 = torch.tensor([[5.0, 6.0], [7.0, 8.0], [11.0, 12.0]])


t_mul = t1 @ t2

print(f"Tensor t1:\n{t1}")
print(f"\nTensor t2:\n{t2}")
print("-" * 30)
print(f"\nنتیجه ضرب (t_mul):\n{t_mul}")

Tensor t1:
tensor([[ 1.,  2.,  9.],
        [ 3.,  4., 10.]])

Tensor t2:
tensor([[ 5.,  6.],
        [ 7.,  8.],
        [11., 12.]])
------------------------------

نتیجه ضرب (t_mul):
tensor([[118., 130.],
        [153., 170.]])


In [306]:
t1 = torch.tensor([[1.0, 2.0, 9.0], [3.0, 4.0, 10.0]])
t1t = t1.T
moz1 = t1t @ t1
moz2 = t1 @ t1t
print(moz1)
print("-" * 30)
print(moz2)

tensor([[ 10.,  14.,  39.],
        [ 14.,  20.,  58.],
        [ 39.,  58., 181.]])
------------------------------
tensor([[ 86., 101.],
        [101., 125.]])


In [307]:
v = torch.tensor([1, 2, 3, 4, 5])
v0 = v.unsqueeze(0)
v1 = v.unsqueeze(1)
v_mul = v0 @ v1
print(v)
print(v0)
print(v1)
print(v_mul)

tensor([1, 2, 3, 4, 5])
tensor([[1, 2, 3, 4, 5]])
tensor([[1],
        [2],
        [3],
        [4],
        [5]])
tensor([[55]])


In [308]:
v0sd = v0.squeeze()
v1sd = v1.squeeze()
v_mulsd = v_mul.squeeze()
print(v0sd)
print(v1sd)
print(v_mulsd)
print(v_mul * 2)
v_mul = v_mul * 2
gay = v_mul.squeeze()
print(gay)

tensor([1, 2, 3, 4, 5])
tensor([1, 2, 3, 4, 5])
tensor(55)
tensor([[110]])
tensor(110)


In [309]:
def printrd():
    kos = "-" * 60
    print(f"\n \n \n {kos} \n\n")


moz = torch.rand(1, 4, 25)
moz_reshaped = moz.view(1, 4, 5, 5)
final_quaery = moz_reshaped.transpose(3, 2)
print(moz)
printrd()
print(final_quaery)

tensor([[[0.8727, 0.9573, 0.9399, 0.7671, 0.3993, 0.6133, 0.1781, 0.3523,
          0.0151, 0.5948, 0.8126, 0.8306, 0.8800, 0.2633, 0.9883, 0.6570,
          0.0414, 0.1649, 0.4449, 0.5698, 0.0909, 0.2400, 0.9925, 0.4523,
          0.9193],
         [0.4142, 0.2952, 0.7846, 0.7750, 0.4829, 0.5271, 0.1329, 0.6347,
          0.5149, 0.0478, 0.8209, 0.8229, 0.9277, 0.1401, 0.3227, 0.3841,
          0.3445, 0.1796, 0.2366, 0.2178, 0.7788, 0.0749, 0.4679, 0.6328,
          0.5929],
         [0.1589, 0.1952, 0.0129, 0.1843, 0.5508, 0.5869, 0.5859, 0.2675,
          0.6645, 0.0030, 0.5200, 0.0640, 0.5717, 0.6408, 0.8046, 0.8228,
          0.3886, 0.7831, 0.5993, 0.0392, 0.3430, 0.4906, 0.0490, 0.5131,
          0.6452],
         [0.8968, 0.3772, 0.8966, 0.8234, 0.1367, 0.8201, 0.6689, 0.6984,
          0.3676, 0.6013, 0.8997, 0.8352, 0.0126, 0.1932, 0.8734, 0.9324,
          0.9803, 0.4441, 0.9951, 0.2835, 0.1120, 0.6252, 0.9836, 0.5162,
          0.9648]]])

 
 
 ----------------------------

In [310]:
M = torch.rand(4, 5)
V = torch.tensor([1, 2, 3, 4])

V_col = V.unsqueeze(1)
# V_col1 = V.T
print(M * V_col)
# print(M * V)

tensor([[0.5524, 0.9542, 0.0284, 0.3457, 0.4710],
        [0.5881, 0.0788, 1.7458, 1.8130, 0.7724],
        [2.8115, 2.7931, 1.7058, 1.2651, 2.8995],
        [2.0392, 0.4046, 0.6009, 0.8101, 1.8790]])


In [311]:
x = torch.tensor(2.0, requires_grad=True)
y = 3 * x**2 + 5
print(f"y  {y} \n x : {x},\n gradian x : {x.grad} \n gradian y : {y.backward()}")

y  17.0 
 x : 2.0,
 gradian x : None 
 gradian y : None


In [312]:
import torch

# 1. تعریف تنسور ورودی (Scalar)
x = torch.tensor(2.0, requires_grad=True)

# 2. تعریف عملیات
y = 3 * x**2 + 5

# 3. محاسبه گرادیان: Autograd را اجرا می کند
y.backward()

# 4. پرینت گرادیان نهایی (ذخیره شده در x.grad)
print(f"y: {y.item()}")
print(f"گرادیان x (x.grad): {x.grad.item()}")

y: 17.0
گرادیان x (x.grad): 12.0
